# Generated by Django 4.1.2 on 2023-03-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
