# Generated by Django 4.1.2 on 2023-03-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_alter_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='family_fundname',
            field=models.CharField(default='Fund Name', max_length=20),
        ),
    ]
