# Generated by Django 4.1.2 on 2023-03-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_accounts_family_fundname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='expensee',
        ),
        migrations.AddField(
            model_name='expenses',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignment.accounts'),
            preserve_default=False,
        ),
    ]
