# Generated by Django 4.1.2 on 2023-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_remove_expenses_expensee_expenses_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_expense',
            field=models.IntegerField(default=0),
        ),
    ]
