# Generated by Django 4.1.2 on 2023-03-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_user_personal_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
