# Generated by Django 4.1.2 on 2023-03-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_alter_expenses_account_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='family_fund',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='saved_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignment.accounts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_expense',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
