# Generated by Django 4.1.2 on 2023-03-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_alter_accounts_family_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='goal_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='saved_money',
            field=models.FloatField(default=0),
        ),
    ]
